### ISSUE TITLE
Can't show replay button at the end of the movie

### ISSUE THREAD

**Issue by herikutu** [kaltura/kdp#25]
I use rtmp streaming.
When the movie reaches at the end of it,the loading spinner appears and stays there.

If I use http provressive download,It goes good.

What shall I do to solve the trouble?

(Now, I put flashvars "disablePlayerSpinner=true", so the spinner doesn't appear.But I want the replay button.)

**Comment by MichalRadwantzor** [comment]
Can you share a link?

**Comment by herikutu** [comment]
Thank you for your response.
Please check the link below.
http://challenge.herikutu.com/

**Comment by MichalRadwantzor** [comment]
This is not a KDP issue. The player doesn't receive "NetStream.Play.Complete" event so it remains in loading state. This should be fixed in FMS / red5.
Here is a thread that might be useful: https://code.google.com/p/red5/issues/detail?id=378
