### ISSUE TITLE
About KDP3 build issues

### ISSUE THREAD

**Issue by developerworks** [kaltura/kdp#29]
### Flash Builder 4.6

```
${KDP_GIT_ROOT}/kdp3Lib/src/com/yahoo/astra/fl/controls/containerClasses/ButtonBar.as:226: Overriding a function that is not marked for override
```

```
${KDP_GIT_ROOT}/KDP3/src/ApplicationLoader.as:199: Access of possibly undefined property PRELOADER_LOADED through a reference with static type Class
```

Dev env:

OS: Mac OSX 10.9
Flash Builder 4.6
SDK used: `/Applications/Adobe Flash Builder 4.6/sdks/4.6.0`
### Flash Builder 4.7

```
${KDP_GIT_ROOT}/KDP3/build_KDP.xml:28: java.lang.NullPointerException
```

**Comment by MichalRadwantzor** [comment]
For Flash Builder 4.6:
if you build manually, make sure you have the following configuration in "kdp3Lib" project, under "additional compiler arguments":
-define=CONFIG::isSDK45,false -define=CONFIG::isSDK46,true
If you use "build_KDP.xml" script, make sure you comment out 4.5 sdk and uncomment sdk 4.6, here:
https://github.com/kaltura/kdp/blob/master/KDP3/build_KDP.xml#L3
Also, don't compile these plugins:
https://github.com/kaltura/kdp/blob/master/KDP3/build_KDP.xml#L135

**Comment by developerworks** [comment]
Thank you!

I replace my 4.6 sdk with 4.5.1A
