### ISSUE TITLE
iPad issues

### ISSUE THREAD

**Issue by desingraj** [kaltura/kdp#32]
Hi, 

I am using the html5 library version 2.4.1 as of now, and I am having problem in iPad playback. 

Everything works fine in PC's and other flash enabled devices. In iPad I am getting error while playing the video.

![untitled](https://cloud.githubusercontent.com/assets/4374605/4215502/0a7761f2-38cf-11e4-8177-747784202fb9.png)

Can anyone experienced this or any suggestions to outcome from this problem?

**Comment by desingraj** [comment]
Any suggestions on this from the professionals?

**Comment by MichalRadwantzor** [comment]
Hi @desingraj , KDP is the Flash desktop player. Please open this issue in HTML5 repo:
https://github.com/kaltura/mwEmbed/issues
