### ISSUE TITLE
HTML5 player don't report errors

### ISSUE THREAD

**Issue by agalera-nice** [kaltura/kdp#35]
Hi, is there any reason why the HTML5 does not report errors as Flash player does?

I registered a JS listener in order to listened for different events of the player, I am focused on tracking the possible errors:

SmartPlugin.kdp.addJsListener("playerStateChange", "SmartPlugin.kalturaPlayerStateChanged")
SmartPlugin.kdp.addJsListener("mediaError", "SmartPlugin.kalturaMediaError")         

With Flash player both listeners are executed when forcing an error, however with HTML5 neither callbacks are  called when an error is forced.

BTW, the way to force an error is to reproduce normally and then shutdown the internet connection with Chrome Network Emulator

Thank you

**Comment by MichalRadwantzor** [comment]
This question should be asked in HTML5 repository: https://github.com/kaltura/mwEmbed
I can tell you that the HTML5 sends "embedPlayerError" event in version 2.21 and up.
