### ISSUE TITLE
FEC-201 Support HLS in KDP

### ISSUE THREAD

**Issue by mdale** [kaltura/kdp#5]
Flash supports a robust AppendBytes api for h.264 playback and can be used to transmux and play HLS segments  

Supporting HLS in flash KDP should enable a flag to force HLS, as well as seamless fallback to HLS when HDS is not available in the entry data.  

The demo page for this feature should look like this sample: http://osmfhls.kutu.ru/
Notice the api for "manual" and "auto" source switching, as well as a listing of the bitrates available. This is important api for our new player skin.  

I did a quick survey of open source based OSMF HLS players and the denivip looks promising: 

code: 
 https://github.com/denivip/osmf-hls-plugin
blog post: 
 http://blog.denivip.ru/index.php/2013/05/osmf-hls-plugin/?lang=en

Alternatively there are commercial implementations but they are generally expensive. Since this code is osmf base plugin, we hope it won't be a lot of work to integrate. 

Testing / QA : The plugin claims to support DVR, Live broadcasts as well as VOD. 
We should test against all these types of HLS streams.

**Comment by mdale** [comment]
from @MichalRadwantzor 

The plugin works, but there are some playback issues.
See example here:
http://projects.kaltura.com/MichalR/hlsTest.html

I noticed that sometimes I get pink squares on the screen. Also seek doesn't work but maybe its a KDP issue.
In addition, kaltura's m3u8 playback was very very bad but I'm  not sure if I built the url wrong or the problem was with the flavors. This is the URL I tried: http://cdnbakmi.kaltura.com/p/524241/sp/52424100/playManifest/entryId/0_r1ss0uv1/flavorIds/0_r1ss0uv1,0_r1ss0uv1/format/applehttp/protocol/http/a.m3u8
Eventually I took some m3u8 from the web and this is what you see playing: http://184.72.239.149/vod/smil:BigBuckBunny.smil/playlist.m3u8

**Comment by nned** [comment]
Hello!
Trying to use KDP for playing HLS.
Both plugins - from kutu and from denivip play m3u8 files.

But there is major issue - seek is not working at all.

**Comment by MichalRadwantzor** [comment]
Hi,
can you try to pass this Flashvar:
ignoreStreamerTypeForSeek=true

**Comment by nned** [comment]
MichalRadwantzor, THANK YOU!!!

worked as a charm - both plugin now seek properly.
I have spent many hours on solving this problem.

Very grateful to you,
have a nice day!)

**Comment by desingraj** [comment]
Great post,

I downloaded the plugin code from https://github.com/denivip/osmf-hls-plugin. Where it would be pasted under Kaltura path and I am not able to see any .swf files associated with this downloaded source.

**Comment by MichalRadwantzor** [comment]
Hi desingraj,
I see the swf is here: 
https://github.com/denivip/osmf-hls-plugin/tree/master/release

To use OSMF plugins with Kaltura you should include KDP's  "genericOSMF" plugin: http://knowledge.kaltura.com/adding-genericosmf-plugin-kdp
and set the pluginURL to the OSMF plugin swf.

**Comment by mdale** [comment]
Note to @desingraj we will soon be releasing an integrated OSMF HLS solution, stay tuned.

**Comment by desingraj** [comment]
The stream works on the code you provide in this post (http://projects.kaltura.com/MichalR/hlsTest.html) 

I just Changed the entryId to my HLS stream, it plays well.. Here it is for your reference.
http://uniqueegroup.com/KALhls.html

But I am not sure, why it doesn't work out for the same m3u8 stream here (http://uniqueegroup.com/HLSown.html) , even after I added the plugin code in uiConf.
Plugin id="genericOSMF"   width="0" height="0"   loadingPolicy="preInitialize" asyncInit="true"
  pluginURL="http://projects.kaltura.com/MichalR/HLSDynamicPlugin.swf" />.

**Comment by MichalRadwantzor** [comment]
Are you sure you added the "genericOSMF" plugin properly to your uiconf? 
your test page worked for me after I added the plugin with these flashvars:
    "genericOSMF.plugin": "true",
    "genericOSMF.relativeTo": "statistics",
    "genericOSMF.position": "after",
    "genericOSMF.asyncInit": "true",
    "genericOSMF.loadingPolicy": "preInitialize",

So I guess it wasn't part of the uiconf.

**Comment by MichalRadwantzor** [comment]
I can't access this page: http://uniqueegroup.com/hls.html
get access forbidden.
I'm not sure I understood the issue, can you elaborate?

**Comment by desingraj** [comment]
Apologies for permission, now its having public access.. Can you please check now?

**Comment by desingraj** [comment]
I have a swf here but not able to play videos http://uniqueegroup.com/HLSDynamicPlugin.swf

**Comment by maryhansen** [comment]
Thank you all for the gateway that  I am understanding HLS in KDP.  I am using the HLSDynamicPlugin.swf from project.kaltura.com, similarly Mr.Michal has used for the testpage. 

Everything going great, I am succeeded in HLS. But the flavors are not changed while I toggle the flavors in player. Only lower bitrate asset is playing even after I changed the high quality asset.

Is there any special flashVariable needs to pass in KWidget.

Thanks in advance
Mary

**Comment by maryhansen** [comment]
Can you guys help me here?

**Comment by MichalRadwantzor** [comment]
Hi, KDP doesn't support flavor switching with HLS Plugin.

**Comment by maryhansen** [comment]
May I use in html5 player for web to stream the HLS?

Also is there any alternate way to do flavor switching in HLS with any special plugin? because I have 15mb download speed of internet connection but my entry plays only lower bitrate(500)

**Comment by MichalRadwantzor** [comment]
We are currently working on Integrating OSMF HLS plugin into our HTML5 lib, it should support flavor switching, I will update you on the expected release date.

**Comment by maryhansen** [comment]
Great... I am waiting for this update...

**Comment by maryhansen** [comment]
I am delivering 1600 and 2600 bitrate assets to play in KDP for HLS streaming using access control. Its playing in web but not in iPad...

In web, it strucks often and freezes at various timeline, I need to refresh the page then seek for the position where I got struck,  to continue watching. 

I am also not able to switch flavors in HDS too, but in SAAS I can do that....

**Comment by MichalRadwantzor** [comment]
The HLS plugin you use is not our plugin. Let's wait for our HLS plugin release and see if it works properly.

**Comment by desingraj** [comment]
Hi,

May I know Kaltura HLS plugin is available now? So that I can use this plugin for my smooth playback to devices and PC's.

**Comment by MichalRadwantzor** [comment]
Hi @desingraj,
the plugin is available in the HTML5 lib.  
https://github.com/kaltura/mwEmbed/
To use it with chromeless Flash player add this var:
LeadWithHLSOnFlash=true

**Comment by desingraj** [comment]
Can I download the latest HTML5 version and use it for my Kaltura server?

Would it be available with the HLS plugin itself?

**Comment by MichalRadwantzor** [comment]
Yes.
Please open all HTML5 related issues in mwEmbed repo.
